apiVersion: v1
kind: Service
metadata:
  name: {{ include "green-thumb.frontend.fullname" . }}
  labels:
    {{- include "green-thumb.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "green-thumb.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      name: http
