/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Start the OIDC flow: stash state/nonce/PKCE in a signed cookie, redirect to Zitadel.
         */
        get: operations["login_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dev Login
         * @description Local-only: provision a demo user and set a session cookie, bypassing OIDC.
         *
         *     Guarded by DEV_AUTH_BYPASS; returns 404 when disabled so the route is inert
         *     in any real deployment. Reuses a fixed oidc_sub so seeded demo data attaches
         *     to this user.
         */
        get: operations["dev_login_auth_dev_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Finish the OIDC flow: validate state, exchange the code, upsert the user, set the session.
         */
        get: operations["callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logout
         * @description Clear the session cookie and send the browser to Zitadel's end-session endpoint.
         */
        get: operations["logout_auth_logout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Return the current user's profile and notification preferences.
         */
        get: operations["read_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Update notification preferences (the only user-editable fields).
         */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/auth/api-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint Api Token
         * @description Mint a long-lived bearer token for headless API access by the current user.
         *
         *     Stateless and shown only once — the server keeps no copy. Rotate
         *     SESSION_SECRET_KEY to revoke (invalidates all tokens and sessions).
         */
        post: operations["mint_api_token_auth_api_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Locations
         * @description List all locations with their plant counts.
         */
        get: operations["list_locations_api_v1_locations_get"];
        put?: never;
        /**
         * Create Location
         * @description Create a location.
         */
        post: operations["create_location_api_v1_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Location
         * @description Delete a location; plants that lived there keep existing without a location.
         */
        delete: operations["delete_location_api_v1_locations__location_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Location
         * @description Update a location's name/description.
         */
        patch: operations["update_location_api_v1_locations__location_id__patch"];
        trace?: never;
    };
    "/api/v1/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Species
         * @description List species with plant counts, optionally filtered by a name search term.
         */
        get: operations["list_species_api_v1_species_get"];
        put?: never;
        /**
         * Create Species
         * @description Create a species.
         */
        post: operations["create_species_api_v1_species_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/species/{species_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Species
         * @description Fetch one species.
         */
        get: operations["get_species_api_v1_species__species_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Species
         * @description Delete a species; plants that referenced it keep existing unlinked.
         */
        delete: operations["delete_species_api_v1_species__species_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Species
         * @description Apply a partial update to a species.
         */
        patch: operations["update_species_api_v1_species__species_id__patch"];
        trace?: never;
    };
    "/api/v1/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plants
         * @description List plants, filterable by location, tag, and a name/species search term.
         */
        get: operations["list_plants_api_v1_plants_get"];
        put?: never;
        /**
         * Create Plant
         * @description Create a plant; a linked species seeds reminders from its default intervals.
         */
        post: operations["create_plant_api_v1_plants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{plant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plant
         * @description Plant detail including the last care event per event type and the linked species.
         */
        get: operations["get_plant_api_v1_plants__plant_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Plant
         * @description Delete a plant; photos, logs and reminders cascade at the database level.
         */
        delete: operations["delete_plant_api_v1_plants__plant_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Plant
         * @description Apply a partial update to a plant.
         */
        patch: operations["update_plant_api_v1_plants__plant_id__patch"];
        trace?: never;
    };
    "/api/v1/plants/{plant_id}/apply-species-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Species Defaults
         * @description Materialize the linked species' default intervals as reminders.
         *
         *     Existing reminders for the same event types are left untouched, so this is
         *     safe to call repeatedly (e.g. after linking a species to an older plant).
         */
        post: operations["apply_species_defaults_api_v1_plants__plant_id__apply_species_defaults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{plant_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Cover Photo
         * @description Set the cover photo; it must be an existing photo of this plant.
         */
        post: operations["set_cover_photo_api_v1_plants__plant_id__cover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{plant_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Photos
         * @description List photo metadata for a plant (bytes are served by GET /photos/{id}).
         */
        get: operations["list_photos_api_v1_plants__plant_id__photos_get"];
        put?: never;
        /**
         * Upload Photo
         * @description Upload a photo (multipart/form-data) and store it as bytea.
         */
        post: operations["upload_photo_api_v1_plants__plant_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Photo
         * @description Serve the display-sized photo bytes with the stored Content-Type.
         */
        get: operations["serve_photo_api_v1_photos__photo_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Photo
         * @description Delete a photo, clearing it as cover photo where referenced.
         */
        delete: operations["delete_photo_api_v1_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{photo_id}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Photo Thumbnail
         * @description Serve the small thumbnail variant for grids and cards.
         */
        get: operations["serve_photo_thumbnail_api_v1_photos__photo_id__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{plant_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Logs
         * @description List care logs for a plant, newest first.
         */
        get: operations["list_logs_api_v1_plants__plant_id__logs_get"];
        put?: never;
        /**
         * Create Log
         * @description Record a care event; logged_at defaults to now and may be backdated.
         */
        post: operations["create_log_api_v1_plants__plant_id__logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Log
         * @description Delete a care log entry.
         */
        delete: operations["delete_log_api_v1_logs__log_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{plant_id}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reminders
         * @description List reminders for a plant with their computed next-due timestamps.
         */
        get: operations["list_reminders_api_v1_plants__plant_id__reminders_get"];
        put?: never;
        /**
         * Create Reminder
         * @description Create a reminder for a plant.
         */
        post: operations["create_reminder_api_v1_plants__plant_id__reminders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{reminder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Reminder
         * @description Delete a reminder.
         */
        delete: operations["delete_reminder_api_v1_reminders__reminder_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Reminder
         * @description Update a reminder's interval, event type, or enabled flag.
         */
        patch: operations["update_reminder_api_v1_reminders__reminder_id__patch"];
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Aggregate dashboard data; upcoming_days is raised by the calendar view.
         */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Push Public Key
         * @description VAPID public key for PushManager.subscribe(); null hides the push UI.
         */
        get: operations["get_push_public_key_api_v1_notifications_push_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Push Subscription
         * @description Register (or re-register) this device's push subscription.
         *
         *     Upserts on the endpoint: browsers rotate subscription details and a
         *     re-subscribe after clearing site data must not create duplicates.
         */
        post: operations["create_push_subscription_api_v1_notifications_push_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Push Subscription
         * @description Remove a subscription by endpoint (idempotent: unknown endpoints 204).
         */
        post: operations["delete_push_subscription_api_v1_notifications_push_unsubscribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Test Notification
         * @description Send a test notification over every channel the user has configured.
         */
        post: operations["send_test_notification_api_v1_notifications_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiTokenRead
         * @description A freshly minted API token. Shown once; the server keeps no copy.
         */
        ApiTokenRead: {
            /** Token */
            token: string;
        };
        /** Body_upload_photo_api_v1_plants__plant_id__photos_post */
        Body_upload_photo_api_v1_plants__plant_id__photos_post: {
            /** File */
            file: string;
        };
        /**
         * CareLogCreate
         * @description Payload to log a care event; logged_at may be backdated and defaults to now.
         */
        CareLogCreate: {
            /** Event Type */
            event_type: string;
            /** Notes */
            notes?: string | null;
            /** Logged At */
            logged_at?: string | null;
        };
        /**
         * CareLogRead
         * @description A recorded care event.
         */
        CareLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plant Id
             * Format: uuid
             */
            plant_id: string;
            /** Event Type */
            event_type: string;
            /** Notes */
            notes: string | null;
            /**
             * Logged By
             * Format: uuid
             */
            logged_by: string;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CoverPhotoUpdate
         * @description Payload for POST /plants/{id}/cover.
         */
        CoverPhotoUpdate: {
            /**
             * Photo Id
             * Format: uuid
             */
            photo_id: string;
        };
        /**
         * DashboardSummary
         * @description Aggregate view backing the dashboard page.
         */
        DashboardSummary: {
            /** Overdue */
            overdue: components["schemas"]["ReminderStatus"][];
            /** Upcoming */
            upcoming: components["schemas"]["ReminderStatus"][];
            /** Recently Watered */
            recently_watered: components["schemas"]["RecentCare"][];
            /** Total Plants */
            total_plants: number;
            /** Total Locations */
            total_locations: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LocationCreate
         * @description Payload to create a location.
         */
        LocationCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * LocationRead
         * @description A location plus its plant count (the list page shows counts).
         */
        LocationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Plant Count
             * @default 0
             */
            plant_count: number;
        };
        /**
         * LocationUpdate
         * @description Partial update for a location.
         */
        LocationUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * PhotoRead
         * @description Photo metadata; the image itself is served by GET /photos/{photo_id}.
         */
        PhotoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plant Id
             * Format: uuid
             */
            plant_id: string;
            /** Mime Type */
            mime_type: string;
            /**
             * Uploaded By
             * Format: uuid
             */
            uploaded_by: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * PlantCreate
         * @description Payload to create a plant.
         *
         *     Linking a species materializes its default care intervals as reminders.
         */
        PlantCreate: {
            /** Name */
            name: string;
            /** Species Name */
            species_name?: string | null;
            /** Scientific Name */
            scientific_name?: string | null;
            /** Species Id */
            species_id?: string | null;
            /** Location Id */
            location_id?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * PlantDetail
         * @description Plant detail: last care event per event type, plus the linked species.
         *
         *     The species is embedded so the detail page can render care guidance
         *     without a second request.
         */
        PlantDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Species Name */
            species_name: string | null;
            /** Scientific Name */
            scientific_name: string | null;
            /** Species Id */
            species_id: string | null;
            /** Location Id */
            location_id: string | null;
            /** Notes */
            notes: string | null;
            /** Tags */
            tags: string[];
            /** Cover Photo Id */
            cover_photo_id: string | null;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Events */
            last_events?: {
                [key: string]: string;
            };
            species?: components["schemas"]["SpeciesRead"] | null;
        };
        /**
         * PlantListItem
         * @description Plant card data.
         *
         *     Includes the last watering for the 'X days ago' indicator and the species
         *     label resolved from the linked species or the free-text fallback.
         */
        PlantListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Species Name */
            species_name: string | null;
            /** Scientific Name */
            scientific_name: string | null;
            /** Species Id */
            species_id: string | null;
            /** Location Id */
            location_id: string | null;
            /** Notes */
            notes: string | null;
            /** Tags */
            tags: string[];
            /** Cover Photo Id */
            cover_photo_id: string | null;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Watered At */
            last_watered_at?: string | null;
            /** Species Display Name */
            species_display_name?: string | null;
        };
        /**
         * PlantRead
         * @description Full plant representation.
         */
        PlantRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Species Name */
            species_name: string | null;
            /** Scientific Name */
            scientific_name: string | null;
            /** Species Id */
            species_id: string | null;
            /** Location Id */
            location_id: string | null;
            /** Notes */
            notes: string | null;
            /** Tags */
            tags: string[];
            /** Cover Photo Id */
            cover_photo_id: string | null;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PlantUpdate
         * @description Partial update for a plant; only provided fields are changed.
         */
        PlantUpdate: {
            /** Name */
            name?: string | null;
            /** Species Name */
            species_name?: string | null;
            /** Scientific Name */
            scientific_name?: string | null;
            /** Species Id */
            species_id?: string | null;
            /** Location Id */
            location_id?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * PushKeys
         * @description Client keys from PushManager.subscribe().
         */
        PushKeys: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /**
         * PushPublicKey
         * @description VAPID application server key; null when Web Push is not configured.
         */
        PushPublicKey: {
            /** Key */
            key: string | null;
        };
        /**
         * PushSubscriptionCreate
         * @description A browser PushSubscription, in the shape subscription.toJSON() emits.
         */
        PushSubscriptionCreate: {
            /** Endpoint */
            endpoint: string;
            keys: components["schemas"]["PushKeys"];
        };
        /**
         * PushSubscriptionRead
         * @description Stored subscription (keys omitted; the client never needs them back).
         */
        PushSubscriptionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Endpoint */
            endpoint: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PushUnsubscribe
         * @description Payload to remove a subscription by its endpoint.
         */
        PushUnsubscribe: {
            /** Endpoint */
            endpoint: string;
        };
        /**
         * RecentCare
         * @description A recent care event for the dashboard's 'recently watered' list.
         */
        RecentCare: {
            /**
             * Plant Id
             * Format: uuid
             */
            plant_id: string;
            /** Plant Name */
            plant_name: string;
            /** Event Type */
            event_type: string;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
        };
        /**
         * ReminderCreate
         * @description Payload to create a reminder.
         */
        ReminderCreate: {
            /** Event Type */
            event_type: string;
            /** Interval Days */
            interval_days: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * ReminderRead
         * @description A reminder as stored.
         */
        ReminderRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plant Id
             * Format: uuid
             */
            plant_id: string;
            /** Event Type */
            event_type: string;
            /** Interval Days */
            interval_days: number;
            /** Enabled */
            enabled: boolean;
            /** Last Notified At */
            last_notified_at: string | null;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReminderStatus
         * @description A reminder enriched with its computed due state for dashboard/calendar views.
         */
        ReminderStatus: {
            /**
             * Reminder Id
             * Format: uuid
             */
            reminder_id: string;
            /**
             * Plant Id
             * Format: uuid
             */
            plant_id: string;
            /** Plant Name */
            plant_name: string;
            /** Event Type */
            event_type: string;
            /** Interval Days */
            interval_days: number;
            /** Last Event At */
            last_event_at: string | null;
            /** Due At */
            due_at: string | null;
            /** Overdue */
            overdue: boolean;
        };
        /**
         * ReminderStatusRead
         * @description A reminder plus its computed schedule, for the plant detail page.
         *
         *     due_at is None when no matching care event exists yet — the reminder is
         *     due immediately, matching the evaluator's overdue rule.
         */
        ReminderStatusRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plant Id
             * Format: uuid
             */
            plant_id: string;
            /** Event Type */
            event_type: string;
            /** Interval Days */
            interval_days: number;
            /** Enabled */
            enabled: boolean;
            /** Last Notified At */
            last_notified_at: string | null;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due At */
            due_at?: string | null;
        };
        /**
         * ReminderUpdate
         * @description Partial update for a reminder.
         */
        ReminderUpdate: {
            /** Event Type */
            event_type?: string | null;
            /** Interval Days */
            interval_days?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * SpeciesCreate
         * @description Payload to create a species.
         */
        SpeciesCreate: {
            /** Name */
            name: string;
            /** Scientific Name */
            scientific_name?: string | null;
            /** Light */
            light?: string | null;
            /** Watering Hint */
            watering_hint?: string | null;
            /** Soil Hint */
            soil_hint?: string | null;
            /**
             * Deadheading
             * @default false
             */
            deadheading: boolean;
            /** Deadheading Hint */
            deadheading_hint?: string | null;
            /** Toxicity */
            toxicity?: string | null;
            /** Common Issues */
            common_issues?: string | null;
            /** Default Intervals */
            default_intervals?: {
                [key: string]: number;
            };
        };
        /**
         * SpeciesListItem
         * @description Species list entry: includes how many plants reference it.
         */
        SpeciesListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scientific Name */
            scientific_name: string | null;
            /** Light */
            light: string | null;
            /** Watering Hint */
            watering_hint: string | null;
            /** Soil Hint */
            soil_hint: string | null;
            /** Deadheading */
            deadheading: boolean;
            /** Deadheading Hint */
            deadheading_hint: string | null;
            /** Toxicity */
            toxicity: string | null;
            /** Common Issues */
            common_issues: string | null;
            /** Default Intervals */
            default_intervals: {
                [key: string]: number;
            };
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Plant Count
             * @default 0
             */
            plant_count: number;
        };
        /**
         * SpeciesRead
         * @description Full species representation.
         */
        SpeciesRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scientific Name */
            scientific_name: string | null;
            /** Light */
            light: string | null;
            /** Watering Hint */
            watering_hint: string | null;
            /** Soil Hint */
            soil_hint: string | null;
            /** Deadheading */
            deadheading: boolean;
            /** Deadheading Hint */
            deadheading_hint: string | null;
            /** Toxicity */
            toxicity: string | null;
            /** Common Issues */
            common_issues: string | null;
            /** Default Intervals */
            default_intervals: {
                [key: string]: number;
            };
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SpeciesUpdate
         * @description Partial update for a species; only provided fields are changed.
         */
        SpeciesUpdate: {
            /** Name */
            name?: string | null;
            /** Scientific Name */
            scientific_name?: string | null;
            /** Light */
            light?: string | null;
            /** Watering Hint */
            watering_hint?: string | null;
            /** Soil Hint */
            soil_hint?: string | null;
            /** Deadheading */
            deadheading?: boolean | null;
            /** Deadheading Hint */
            deadheading_hint?: string | null;
            /** Toxicity */
            toxicity?: string | null;
            /** Common Issues */
            common_issues?: string | null;
            /** Default Intervals */
            default_intervals?: {
                [key: string]: number;
            } | null;
        };
        /**
         * UserRead
         * @description Public profile of the current user, including notification preferences.
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Ntfy Enabled */
            ntfy_enabled: boolean;
            /** Ntfy Topic Override */
            ntfy_topic_override: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserUpdate
         * @description Mutable user preferences; identity fields come from OIDC and are read-only.
         */
        UserUpdate: {
            /** Ntfy Enabled */
            ntfy_enabled?: boolean | null;
            /** Ntfy Topic Override */
            ntfy_topic_override?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dev_login_auth_dev_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_auth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_api_token_auth_api_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenRead"];
                };
            };
        };
    };
    list_locations_api_v1_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"][];
                };
            };
        };
    };
    create_location_api_v1_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_location_api_v1_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_location_api_v1_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_species_api_v1_species_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_species_api_v1_species_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeciesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_species_api_v1_species__species_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                species_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_species_api_v1_species__species_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                species_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_species_api_v1_species__species_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                species_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeciesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plants_api_v1_plants_get: {
        parameters: {
            query?: {
                location_id?: string | null;
                tag?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plant_api_v1_plants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plant_api_v1_plants__plant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plant_api_v1_plants__plant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plant_api_v1_plants__plant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_species_defaults_api_v1_plants__plant_id__apply_species_defaults_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_cover_photo_api_v1_plants__plant_id__cover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverPhotoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_api_v1_plants__plant_id__photos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_api_v1_plants__plant_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_api_v1_plants__plant_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_photo_api_v1_photos__photo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_v1_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_photo_thumbnail_api_v1_photos__photo_id__thumb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_api_v1_plants__plant_id__logs_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_log_api_v1_plants__plant_id__logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_log_api_v1_logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reminders_api_v1_plants__plant_id__reminders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderStatusRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reminder_api_v1_plants__plant_id__reminders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reminder_api_v1_reminders__reminder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_reminder_api_v1_reminders__reminder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                upcoming_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_push_public_key_api_v1_notifications_push_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushPublicKey"];
                };
            };
        };
    };
    create_push_subscription_api_v1_notifications_push_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_push_subscription_api_v1_notifications_push_unsubscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushUnsubscribe"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_notification_api_v1_notifications_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
